name: HaxGame

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: kdlab/setup-haxe@v1

      - name: Build Library
        run: haxe build.hxml

      - name: Test Library
        run: haxe test.hxml

      - name: Publish Library
        uses: actions/upload-artifact@v2
        with:
          name: minhabiblioteca
          path: bin/minhabiblioteca.zip
